# SYNTHETIC posts: (lang, 1=AI 0=human, text)
D = [
("en",1,"It's not just a tool, it's a paradigm shift. Here's the thing: the real unlock is consistency. Curious what you think?"),
("en",1,"Great question! The key insight is that productivity isn't about doing more — it's about doing what matters. Hope this helps!"),
("en",1,"Ship faster. Learn faster. Win faster. The future of work is being rewritten, and quietly, everything changes."),
("en",1,"The hard part isn't writing code. It's deciding what to build. Not features. Not roadmaps. Just clarity."),
("en",1,"Studies show that remote teams are more resilient. The missing piece is trust debt: the gap between intent and action. Thoughts?"),
("en",1,"Here's the shift: leaders who listen build teams that last. It's not about control, it's about connection. What do you think?"),
("en",1,"At the end of the day, great products come from genuine curiosity, robust feedback loops, and a deeply human touch."),
("en",1,"This is such an important point. AI won't replace you; someone using AI will. The real question is: are you ready?"),
("en",1,"Remarkably, the most underrated skill in tech is decision latency. Reduce it, and everything else compounds. Would love to hear how others approach this."),
("en",1,"Three lessons from 10 years in startups: Move fast. Stay curious. Build trust. That's it. That's the post."),
("en",0,"lol my build broke twice on friday and idk why. anyway coffee fixed it"),
("en",0,"ok but who decided airport sandwiches should cost $14?? I paid it. I hate myself"),
("en",0,"nooo not the season finale spoilers in my feed again, i was gonna watch tonight"),
("en",0,"my cousin in leeds just got a tortoise named kevin and honestly kevin is thriving"),
("en",0,"wait no i meant tuesday not thursday. sorry. the meeting is tuesday"),
("en",0,"the bus was 20 min late again so i walked and got rained on, great start to monday"),
("en",0,"hot take: pineapple on pizza is fine and yall are way way too dramatic about it"),
("en",0,"just spent 3 hours debugging a missing semicolon. a semicolon. i need a new career"),
("en",0,"born to nap, forced to attend standup"),
("en",0,"tried the new ramen place downtown. broth was salty af but the egg was perfect. 7/10 would go back"),
("es",1,"No es solo una herramienta, es un cambio de paradigma. La clave real es la constancia. ¿Qué opinas?"),
("es",1,"¡Gran pregunta! La verdad es que la productividad no consiste en hacer más, sino en hacer lo que importa. ¡Espero que ayude!"),
("es",1,"Aprende más rápido. Crece más rápido. Gana más rápido. El futuro del trabajo se está reescribiendo, y todo cambia."),
("es",1,"En última instancia, los mejores productos nacen de una curiosidad genuina y de ciclos de retroalimentación sólidos."),
("es",0,"jajaja mi gato tiró la planta otra vez y me miró como diciendo 'qué'. lo amo pero lo voy a vender"),
("es",0,"alguien sabe por qué el metro está parado?? llevo 20 minutos aquí dentro, ayuda"),
("es",0,"acabo de pagar 12 euros por un café y un croissant en el aeropuerto, me quiero morir"),
("es",0,"me dormí en la reunión y mi jefe me preguntó algo, dije 'sí' y era una pregunta de no. fin"),
("fr",1,"Ce n'est pas qu'un outil, c'est un véritable changement de paradigme. L'essentiel : la constance. Qu'en pensez-vous ?"),
("fr",1,"Excellente question ! Le point clé, c'est que la productivité ne consiste pas à faire plus, mais à faire ce qui compte. J'espère que cela aide !"),
("fr",1,"Avancer plus vite. Apprendre plus vite. Gagner plus vite. L'avenir du travail est en train d'être réécrit."),
("fr",1,"Au final, les meilleurs produits naissent d'une curiosité sincère et de boucles de retour robustes. Curieux d'avoir vos avis."),
("fr",0,"mdrrr j'ai raté mon arrêt de bus parce que j'étais sur mon tel, je suis à 5km de chez moi"),
("fr",0,"quelqu'un sait pourquoi la caf a encore perdu mon dossier?? c'est la 3e fois ce mois"),
("fr",0,"j'ai mangé une baguette entière en rentrant. aucun regret. bonne soirée"),
("fr",0,"mon voisin joue de la trompette à 7h du mat un dimanche, jvais devenir fou"),
("de",1,"Es ist nicht nur ein Werkzeug, es ist ein Paradigmenwechsel. Der eigentliche Schlüssel: Beständigkeit. Was meint ihr?"),
("de",1,"Tolle Frage! Der entscheidende Punkt ist, dass es bei Produktivität nicht darum geht, mehr zu tun, sondern das Wichtige. Ich hoffe, das hilft!"),
("de",1,"Schneller lernen. Schneller wachsen. Schneller gewinnen. Die Zukunft der Arbeit wird neu geschrieben."),
("de",1,"Letztendlich entstehen die besten Produkte aus echter Neugier und robusten Feedbackschleifen. Gerne eure Gedanken dazu."),
("de",0,"die bahn hat mal wieder 40 min verspätung, ich glaub ich laufe einfach. tschüss"),
("de",0,"hab gerade 9 euro für ein sandwich am bahnhof bezahlt, ich fass es nicht haha"),
("de",0,"mein kater sitzt seit stunden vor dem kühlschrank und starrt. er weiss irgendwas"),
("de",0,"meeting war um 3 nicht um 2, sorry für die verwirrung, bin schon da"),
("pt",1,"Não é apenas uma ferramenta, é uma mudança de paradigma. A chave real é a consistência. O que você acha?"),
("pt",1,"Ótima pergunta! O ponto-chave é que produtividade não é fazer mais, é fazer o que importa. Espero que ajude!"),
("pt",1,"No fim das contas, os melhores produtos nascem da curiosidade genuína e de ciclos de feedback robustos."),
("pt",0,"kkkkk perdi o ônibus de novo, tô andando pra casa debaixo de chuva, segunda-feira né"),
("pt",0,"alguém sabe por que o wifi cai todo dia às 8h?? já reiniciei o roteador 3 vezes"),
("pt",0,"paguei 15 reais num pão de queijo no aeroporto e ainda comi em pé. sem comentários"),
("hi",1,"यह सिर्फ़ एक उपकरण नहीं, एक बदलाव है। असली कुंजी निरंतरता है। आप क्या सोचते हैं?"),
("hi",1,"बहुत बढ़िया सवाल! मुख्य बात यह है कि उत्पादकता ज़्यादा करने में नहीं, ज़रूरी काम करने में है। उम्मीद है यह मददगार होगा!"),
("hi",1,"तेज़ सीखें। तेज़ बढ़ें। तेज़ जीतें। काम का भविष्य दोबारा लिखा जा रहा है।"),
("hi",0,"यार आज फिर बस छूट गई, पैदल जा रहा हूँ और बारिश भी शुरू हो गई, सोमवार है ना"),
("hi",0,"किसी को पता है वाईफ़ाई रोज़ सुबह 8 बजे क्यों बंद हो जाता है?? राउटर 3 बार रीस्टार्ट कर लिया"),
("hi",0,"एयरपोर्ट पर सैंडविच के 400 रुपये दिए। खा भी लिया। अब पछता रहा हूँ हाहा"),
]
